import { NextResponse } from 'next/server'

// Supabase PostgREST helper — uses fetch directly to avoid @supabase/supabase-js
// bundling issues in Next.js 14 App Router (createClient webpack resolution).
// Service role key bypasses RLS for anonymous lead capture.
async function sbInsert(table: string, row: object): Promise<{ data: any; error: string | null }> {
  const url = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/${table}`
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'apikey': process.env.SUPABASE_SERVICE_ROLE_KEY!,
      'Authorization': `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY!}`,
      'Content-Type': 'application/json',
      'Prefer': 'return=representation',
    },
    body: JSON.stringify(row),
  })
  if (!res.ok) {
    const msg = await res.text().catch(() => res.statusText)
    return { data: null, error: `${table} insert failed (${res.status}): ${msg}` }
  }
  const rows = await res.json()
  return { data: Array.isArray(rows) ? rows[0] : rows, error: null }
}

export async function POST(req: Request) {
  try {
    const body = await req.json()
    const { org, industry, role, email } = body as {
      org?: string
      industry?: string
      role?: string
      email?: string
    }

    if (!org?.trim() || !email?.trim()) {
      return NextResponse.json(
        { error: 'org and email are required' },
        { status: 400 }
      )
    }

    // 1. Create organisation (owner_id nullable for anonymous capture)
    const { data: orgData, error: orgErr } = await sbInsert('organisations', {
      name: org.trim(),
      domain: email.includes('@') ? email.split('@')[1].toLowerCase() : null,
      plan_type: 'free',
      pack_credits_remaining: 1,
    })
    if (orgErr || !orgData) {
      console.error('org insert:', orgErr)
      return NextResponse.json({ error: 'Failed to create organisation' }, { status: 500 })
    }

    // 2. Create audit
    const { data: auditData, error: auditErr } = await sbInsert('audits', {
      org_id: orgData.id,
      title: `Digital Maturity Audit — ${org.trim()}`,
      department: role?.trim() ?? null,
      status: 'setup',
      interview_count_planned: 1,
      interview_count_completed: 0,
    })
    if (auditErr || !auditData) {
      console.error('audit insert:', auditErr)
      return NextResponse.json({ error: 'Failed to create audit' }, { status: 500 })
    }

    // 3. Create interview — token auto-generated by DB default:
    //    encode(gen_random_bytes(32), 'hex')
    const { data: interviewData, error: intErr } = await sbInsert('interviews', {
      audit_id: auditData.id,
      org_id: orgData.id,
      subject_email: email.trim().toLowerCase(),
      subject_role: role?.trim() ?? null,
      subject_department: industry?.trim() ?? null,
      status: 'scheduled',
    })
    if (intErr || !interviewData) {
      console.error('interview insert:', intErr)
      return NextResponse.json({ error: 'Failed to create interview' }, { status: 500 })
    }

    return NextResponse.json({
      success: true,
      token: interviewData.token,
      auditId: auditData.id,
      orgId: orgData.id,
    })
  } catch (err) {
    console.error('Unexpected capture error:', err)
    return NextResponse.json({ error: 'Unexpected error' }, { status: 500 })
  }
}
