import { createClient } from '@supabase/supabase-js'
import { NextResponse } from 'next/server'

// Service role client — bypasses RLS for anonymous lead capture.
// Never expose this key client-side.
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export async function POST(req: Request) {
  try {
    const body = await req.json()
    const { org, industry, role, email } = body as {
      org?: string
      industry?: string
      role?: string
      email?: string
    }

    if (!org?.trim() || !email?.trim()) {
      return NextResponse.json(
        { error: 'org and email are required' },
        { status: 400 }
      )
    }

    // 1. Create organisation (owner_id nullable — anonymous capture)
    const { data: orgData, error: orgError } = await supabase
      .from('organisations')
      .insert({
        name: org.trim(),
        domain: email.includes('@') ? email.split('@')[1].toLowerCase() : null,
        plan_type: 'free',
        pack_credits_remaining: 1,
      })
      .select('id')
      .single()

    if (orgError) {
      console.error('org insert error:', orgError)
      return NextResponse.json({ error: 'Failed to create organisation' }, { status: 500 })
    }

    // 2. Create audit
    const { data: auditData, error: auditError } = await supabase
      .from('audits')
      .insert({
        org_id: orgData.id,
        title: `Digital Maturity Audit — ${org.trim()}`,
        department: role?.trim() ?? null,
        status: 'setup',
        interview_count_planned: 1,
        interview_count_completed: 0,
      })
      .select('id')
      .single()

    if (auditError) {
      console.error('audit insert error:', auditError)
      return NextResponse.json({ error: 'Failed to create audit' }, { status: 500 })
    }

    // 3. Create interview — token is auto-generated by DB default:
    //    encode(gen_random_bytes(32), 'hex')
    const { data: interviewData, error: interviewError } = await supabase
      .from('interviews')
      .insert({
        audit_id: auditData.id,
        org_id: orgData.id,
        subject_email: email.trim().toLowerCase(),
        subject_role: role?.trim() ?? null,
        subject_department: industry?.trim() ?? null,
        status: 'scheduled',
      })
      .select('id, token')
      .single()

    if (interviewError) {
      console.error('interview insert error:', interviewError)
      return NextResponse.json({ error: 'Failed to create interview' }, { status: 500 })
    }

    return NextResponse.json({
      success: true,
      token: interviewData.token,
      auditId: auditData.id,
      orgId: orgData.id,
    })
  } catch (err) {
    console.error('Unexpected capture error:', err)
    return NextResponse.json({ error: 'Unexpected error' }, { status: 500 })
  }
}
