import type { Metadata } from 'next'

type Props = {
  params: { id: string }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  return {
    title: `AI Readiness Report | Connai`,
    description:
      'View your personalised AI readiness report — detailed findings, scoring, and recommendations generated by Connai.',
    robots: { index: false, follow: false },
  }
}

export default function ReportIdLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
