import type { Metadata } from 'next'

type Props = {
  params: Promise<{ id: string }>
}

const SITE_URL = 'https://connai.linkgrow.io'

// ─── Supabase REST helper (server-side, no SDK needed) ───────────────────────
// Reads org_name + overall_score from the public leads table.
// createClient is NOT used at module level — all DB access is inside generateMetadata.
async function fetchLeadMetaServer(id: string): Promise<{
  orgName: string | null
  score: number | null
}> {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  if (!supabaseUrl || !anonKey) return { orgName: null, score: null }
  try {
    const url = `${supabaseUrl}/rest/v1/leads?id=eq.${encodeURIComponent(id)}&select=org_name,overall_score&limit=1`
    const res = await fetch(url, {
      headers: {
        apikey: anonKey,
        Authorization: `Bearer ${anonKey}`,
        Accept: 'application/json',
      },
      next: { revalidate: 60 }, // cache for 60s — score rarely changes after completion
    })
    if (!res.ok) return { orgName: null, score: null }
    const rows = await res.json()
    const row = Array.isArray(rows) ? rows[0] : null
    return {
      orgName: row?.org_name ?? null,
      score: typeof row?.overall_score === 'number' ? row.overall_score : null,
    }
  } catch {
    return { orgName: null, score: null }
  }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params
  const { orgName, score } = await fetchLeadMetaServer(id)

  // Build dynamic OG image URL — passes leadId so the edge OG route can render
  // the real score and company name. Falls back gracefully if Supabase is unavailable.
  const ogParams = new URLSearchParams({ leadId: id })
  const ogImageUrl = `${SITE_URL}/api/og?${ogParams.toString()}`

  const reportUrl = `${SITE_URL}/report/${id}`
  const titleCompany = orgName ? `${orgName} — ` : ''
  const titleScore = score !== null ? ` (Score: ${score}/100)` : ''
  const title = `${titleCompany}AI Readiness Report${titleScore} | Connai`
  const description = orgName
    ? `${orgName}'s digital maturity report — AI-powered scoring across 8 dimensions with prioritised recommendations.`
    : 'View your personalised AI readiness report — detailed findings, scoring, and recommendations generated by Connai.'

  return {
    title,
    description,
    robots: { index: false, follow: false },
    openGraph: {
      type: 'website',
      url: reportUrl,
      siteName: 'Connai',
      title,
      description,
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: orgName
            ? `${orgName} Digital Maturity Report | Connai`
            : 'AI Readiness Report | Connai',
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImageUrl],
    },
  }
}

export default function ReportIdLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
