import { NextRequest, NextResponse } from 'next/server'
import { rateLimit } from '@/lib/rate-limit'
import { jsPDF } from 'jspdf'

export const dynamic = 'force-dynamic'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? 'https://mhuofnkbjbanrdvvktps.supabase.co'
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY


export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const ip = req.headers.get('x-forwarded-for')?.split(',')[0] ?? 'unknown'
  if (!rateLimit(ip, 'report-pdf', 3)) {
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 })
  }
  if (!SUPABASE_SERVICE_ROLE_KEY) return NextResponse.json({ error: 'Server configuration error' }, { status: 500 })
  const { id } = await params
  let rows
  try {
    const res = await fetch(
      `${SUPABASE_URL}/rest/v1/reports?lead_id=eq.${id}&select=overall_score,dimension_scores,leads(org_name)&limit=1`,
      { headers: { apikey: SUPABASE_SERVICE_ROLE_KEY, Authorization: `Bearer ${SUPABASE_SERVICE_ROLE_KEY}` } }
    )
    rows = await res.json()
  } catch (e) { return NextResponse.json({ error: 'Database error' }, { status: 500 }) }
  if (!rows || rows.length === 0 || rows.error) return NextResponse.json({ error: 'Report not found' }, { status: 404 })
  const report = rows[0]
  const orgName: string = (report.leads as { org_name?: string } | null)?.org_name ?? 'Organization'
  const overall: number = report.overall_score ?? 0
  const dims: Record<string, number> = report.dimension_scores ?? {}
  let doc: InstanceType<typeof jsPDF>
  try { doc = new jsPDF({ unit: 'mm', format: 'a4' }) } catch (e) { return NextResponse.json({ error: 'PDF generation unavailable' }, { status: 500 }) }
  const teal = [13, 92, 99] as const
  const accent = [78, 205, 196] as const
  doc.setFillColor(...teal); doc.rect(0, 0, 210, 30, 'F')
  doc.setFontSize(20); doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.text('CONNAI', 105, 14, { align: 'center' })
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.text('Digital Maturity Report', 105, 22, { align: 'center' })
  doc.setFontSize(16); doc.setTextColor(30, 30, 30); doc.setFont('helvetica', 'bold'); doc.text(orgName, 105, 46, { align: 'center' })
  doc.setFontSize(10); doc.setTextColor(100, 116, 139); doc.setFont('helvetica', 'normal'); doc.text('OVERALL SCORE', 105, 58, { align: 'center' })
  doc.setFontSize(36); doc.setTextColor(...teal); doc.setFont('helvetica', 'bold'); doc.text(`${overall}`, 105, 72, { align: 'center' })
  doc.setFontSize(12); doc.setTextColor(100, 116, 139); doc.text('/100', 120, 72)
  let y = 88
  doc.setFontSize(12); doc.setTextColor(30, 30, 30); doc.setFont('helvetica', 'bold'); doc.text('Dimension Scores', 20, y); y += 8
  for (const [name, score] of Object.entries(dims)) {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.setFontSize(9); doc.setTextColor(60, 60, 60); doc.setFont('helvetica', 'normal'); doc.text(name, 20, y)
    doc.setFillColor(230, 230, 230); doc.rect(80, y - 4, 100, 5, 'F')
    const n = typeof score === 'number' ? score : 0
    doc.setFillColor(...accent); doc.rect(80, y - 4, n, 5, 'F')
    doc.setFontSize(9); doc.setTextColor(...teal); doc.setFont('helvetica', 'bold'); doc.text(`${n}`, 184, y)
    y += 10
  }
  doc.setFontSize(8); doc.setTextColor(180, 180, 180); doc.setFont('helvetica', 'normal')
  doc.text(`Generated by Connai · connai.linkgrow.io`, 105, 287, { align: 'center' })
  return new NextResponse(doc.output('arraybuffer'), { headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="connai-report-${orgName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf"` } })
}
